#!/usr/bin/env python3
"""
Generate Golden STEP Baselines

Regenerates the committed STEP exports under examples/validation/golden_step/
— exact-geometry baselines for a small, curated set of anchor models
(VALIDATION_STRENGTHENING.md section 4.9). Volume/bbox/mesh-hash contracts
can miss a pure topology regression (an extra face, a fillet that silently
stops applying to one edge); a STEP baseline plus BREP entity-count
comparison (tiacad_core/testing/golden_step.py) catches that class of bug.

Deliberately *not* auto-generated by the test suite: a golden must only
change because a human ran this script, looked at the diff (topology
counts printed below, and `git diff --stat` on the STEP file), and decided
the new build is correct — not because a test silently re-baselined itself.
Keep this set tiny (see 4.9): it is a supplement to the oracle-based
contracts, not a replacement.

Usage:
    # Regenerate every anchor model
    python scripts/generate_golden_steps.py

    # Regenerate a single anchor
    python scripts/generate_golden_steps.py --model examples/validation/T3_lego_2x1.tiacad

Author: TIA
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from tiacad_core.parser.tiacad_parser import TiaCADParser
from tiacad_core.testing.contracts import resolve_contract_part
from tiacad_core.testing.golden_step import export_golden_step, topology_signature

PROJECT_ROOT = Path(__file__).parent.parent
GOLDEN_DIR = PROJECT_ROOT / "examples" / "validation" / "golden_step"

# Curated anchor list — see VALIDATION_STRENGTHENING.md 4.9: "keep the set
# tiny." Chosen for topology diversity, not volume coverage (that's the
# expect: ladder's job): a chamfer/fillet pair (face-count-sensitive
# finishing ops), a composite with real regression history
# (T3_lego_2x1 — previously shipped with 6 disconnected bodies), a
# fillet-on-composite, and a bolted assembly (multi-solid, coaxial fit).
ANCHOR_MODELS = [
    "examples/validation/T1_chamfer.tiacad",
    "examples/validation/T1_fillet.tiacad",
    "examples/validation/T3_lego_2x1.tiacad",
    "examples/validation/T3_bracket_fillet.tiacad",
    "examples/validation/T4_bolted_bracket.tiacad",
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate golden STEP baselines")
    parser.add_argument(
        "--model", "-m", default=None,
        help="Regenerate a single anchor model path only (default: all anchors)",
    )
    args = parser.parse_args()

    paths = [args.model] if args.model else ANCHOR_MODELS

    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Generating {len(paths)} golden STEP baseline(s)...")
    for path in paths:
        doc = TiaCADParser.parse_file(path)
        expect = getattr(doc, "expect", {}) or {}
        part, part_name = resolve_contract_part(doc, expect)

        step_path = GOLDEN_DIR / (Path(path).stem + ".step")
        export_golden_step(part, str(step_path))
        sig = topology_signature(part)
        print(f"  {path}: part={part_name!r} -> {step_path.relative_to(PROJECT_ROOT)} {sig.as_dict()}")

    print("\nNext steps:")
    print("  1. Review the diff (git diff --stat examples/validation/golden_step/) —")
    print("     a changed file means the build changed; confirm that's expected")
    print("     (a deliberate geometry/kernel change) before committing.")
    print("  2. Run 'pytest tiacad_core/tests/test_correctness/test_golden_step.py' to verify.")
    print("  3. Commit the updated STEP file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
