#!/usr/bin/env python3
"""
Update Determinism Golden Hashes

Regenerates tiacad_core/tests/test_correctness/golden_hashes.json — the
reviewed baseline that pins each corpus model's expected volume, bounding
box, and mesh hash (VALIDATION_STRENGTHENING.md section 4.4).

This file is deliberately *not* auto-generated by the test suite: a golden
must only change because a human ran this script, looked at the diff, and
decided the new build is correct (a real geometry/kernel change), not
because a test silently re-baselined itself.

Usage:
    # Regenerate goldens for every model with an expect: block
    python scripts/update_determinism_goldens.py

    # Regenerate a single model
    python scripts/update_determinism_goldens.py --model examples/simple_guitar_hanger.yaml

Author: TIA
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from tiacad_core.testing.contracts import discover_models_with_expect
from tiacad_core.testing.determinism import build_snapshot, golden_snapshot_dict


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate determinism golden hashes")
    parser.add_argument(
        "--model", "-m", default=None,
        help="Regenerate a single model path only (default: every model with an expect: block)",
    )
    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    examples_dir = project_root / "examples"
    golden_path = project_root / "tiacad_core" / "tests" / "test_correctness" / "golden_hashes.json"

    if args.model:
        paths = [args.model]
    else:
        paths = discover_models_with_expect(str(examples_dir))

    if not paths:
        print("No models found (expect: corpus is empty).")
        return 1

    golden = {}
    if args.model and golden_path.exists():
        golden = json.loads(golden_path.read_text())  # partial regen: merge into existing goldens
    # else: full regeneration starts clean rather than accumulating stale entries

    print(f"Building {len(paths)} model(s)...")
    for path in paths:
        rel = str(Path(path).relative_to(project_root)) if Path(path).is_absolute() else path
        snapshot = build_snapshot(path)
        from tiacad_core.parser.tiacad_parser import TiaCADParser
        from tiacad_core.testing.contracts import resolve_contract_part

        doc = TiaCADParser.parse_file(path)
        expect = getattr(doc, 'expect', {}) or {}
        _, part_name = resolve_contract_part(doc, expect)

        golden[rel] = golden_snapshot_dict(snapshot, part_name)
        print(f"  {rel}: part={part_name!r} volume={snapshot.volume:.4f} hash={snapshot.canonical_mesh_hash[:12]}...")

    golden_path.write_text(json.dumps(golden, indent=2, sort_keys=True) + "\n")
    print(f"\nWrote {len(golden)} golden(s) to {golden_path}")
    print("\nNext steps:")
    print("  1. Review the diff (git diff) — a changed hash/volume means the build changed;")
    print("     confirm that's expected (a deliberate geometry/kernel change) before committing.")
    print("  2. Run 'pytest tiacad_core/tests/test_correctness/test_determinism.py' to verify.")
    print("  3. Commit the updated golden_hashes.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
